add/update permalinks to not use .html
musichackathon/mmh_jekyll pull request #36
Opened 2017-05-21 23:47 UTC by therewasaguy

- remove .html extension from events and posts permalinks
- add permalinks for header nav links

2017-05-22 03:05 UTC, khoeger reviewed
The main pages no longer have .html, but specific events, such as February 2017's Music Visualization event or the upcoming Hip Hop Hacks 2017, still end in .html.

2017-05-22 03:09 UTC, therewasaguy commented
@khoeger the files still have .html extensions, but the links that we use shouldn't. Let me know if you see a spot where a link includes ".html".

Both of these links already work, and this PR would just change the permalink so that, throughout the site, we only link to the first one
https://musichackathon.github.io/mmh_jekyll/2017-06-10
https://musichackathon.github.io/mmh_jekyll/2017-06-10.html

2017-05-22 03:16 UTC, khoeger commented
I checked out the branch permalinks, but still got http://localhost:4000/2017-06-10.html. [](url)

2017-05-22 12:40 UTC, therewasaguy commented
Ah, thanks @khoeger good catch. Just updated to use what Jekyll calls "pretty urls" for events and posts. This makes a folder with index.html inside of it. This changes relative paths so I updated `_layouts/event.html` to use absolute path for images

2017-05-23 12:41 UTC, trevorknight requested changes

2017-05-23 12:41 UTC, trevorknight commented on _layouts/event.html
> +    <img src="/assets/events/{{page.image}}"/>
This will break when hosted by github. 

Please use {{ site.github.url }}/assets

2017-05-23 12:41 UTC, trevorknight commented on blog.md
> +permalink: blog
I know this is my fault, not yours, but as long as you're editing this front matter, would be willing to make the pages have the fields in the same order?

2017-06-14 23:00 UTC, trevorknight approved these changes

2017-06-15 21:30 UTC, merged